# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-20.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.14.0'
  displayName: 'Install Node.js'

- script: |
    sudo npm install --unsafe-perm=true --allow-root cypress
  displayName: 'npm install'
  
- script: |
    npx cypress run
  displayName: npx cypress run
  continueOnError: true